spring:
  datasource:
    url: jdbc:mysql://hackathon.cbzvdfiuwkdf.ap-northeast-2.rds.amazonaws.com:3306/hackathon?useSSL=false&serverTimezone=UTC
    username: tomato
    password: tomatotomato
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true